name: mix_workspace

sdkPath: .fvm/flutter_sdk
packages:
  - packages/**
  - examples/**

categories:
  mix_deps:
    - packages/mix
    - packages/mix_annotations
    - packages/mix_generator
  should_test:
    - packages/mix
    - examples/**

command:
  bootstrap:
    environment:
      sdk: ">=3.0.6 <4.0.0"
      flutter: ">=3.10.6"
  publish:
    hooks:
      pre: melos run pre-publish

scripts:
  brb:
    description: Run build_runner for projects that have it as a dependency
    steps:
      - melos run brbc
      - melos exec --depends-on="build_runner" --category="mix_deps" dart run build_runner build --delete-conflicting-outputs
  brbc: 
    run: melos exec --depends-on="build_runner" dart run build_runner clean
    description: Clean build_runner for projects that have it as a dependency
  test:
    run: melos exec --category="should_test" flutter test
    description: Run flutter test in all projects that should be tested
  fix:
    steps:
      - melos exec dart fix --apply .
      - melos exec --depends-on="dart_code_metrics_presets" dcm fix .
  custom_lint_analyze:
    steps: 
      - dart pub global activate custom_lint
      - melos exec --depends-on="mix_lint" custom_lint

  analyze:
    steps: 
      - melos exec --category="mix_deps" dart analyze --fatal-infos .
      - melos exec --category="mix_deps" --depends-on="dart_code_metrics_presets" dcm analyze --fatal-warnings --fatal-style --fatal-performance .
      - melos run custom_lint_analyze

  pre-publish: 
    steps:
      - melos run brbc
      - melos run analyze
      - melos run test
    description: Run a quality check before publishing

  verify_version_pubspec_changelog:
    run: ./scripts/verify_changelogs.sh packages
    description: Verify that all packages have the same version