# yaml-language-server: $schema=./schemas/melos.yaml.schema.json
name: mix_workspace

sdkPath: .fvm/flutter_sdk
packages:
  - packages/*
  - packages/mix/example
  - examples/*
  - packages/*/demo

command:
  bootstrap:
    environment:
      sdk: ">=3.6.0 <4.0.0"
      flutter: ">=3.27.0"
    dev_dependencies:
      flutter_lints: ^4.0.0
      dart_code_metrics_presets: ^2.14.0
      build_runner: ^2.4.9
  publish:
    hooks:
      pre: melos run gen:build

categories:
  flutter_projects: 
    - packages/mix
    - packages/remix
    - packages/mix_lint
    - packages/naked
    - packages/mix_lint_test
    - packages/annotations
  dart_projects:
    - packages/mix_generator

scripts:
  # ANALYSIS
  analyze:
    run: melos run analyze:dart && melos run analyze:dcm
    description: Run all static analysis checks.
    exec:
      failFast: true
      
  analyze:dart:
    run: melos exec -c 4 -- dart analyze .
    description: Run Dart static analysis checks.

  analyze:dcm:
    run: melos exec -c 4 -- dcm analyze . --fatal-style --fatal-performance --fatal-warnings
    description: Run DCM static analysis checks.
    packageFilters:
      dependsOn: "dart_code_metrics_presets"

  lint:fix:all:
    run: melos run lint:dart:fix && melos run lint:dcm:fix
    description: Run all static analysis checks and apply fixes.

  lint:dart:fix:
    run: melos exec -- dart fix --apply .
    description: Run Dart static analysis checks.

  lint:dcm:fix:
    run: melos exec -- dcm fix .
    description: Run DCM static analysis checks.
    packageFilters:
      dependsOn: "dart_code_metrics_presets"

  gen:watch:
    run: melos exec --order-dependents -- dart run build_runner watch --delete-conflicting-outputs
    description: Generate code for all packages
    packageFilters:
      dependsOn: "build_runner"

  gen:build:
    run: melos run gen:clean && melos exec --order-dependents -- dart run build_runner build --delete-conflicting-outputs
    description: Generate code for all packages
    packageFilters:
      dependsOn: "build_runner"

  gen:clean:
    run: melos exec --order-dependents -- dart run build_runner clean
    description: Clean generated code for all packages
    packageFilters:
      dependsOn: "build_runner"

  test:flutter:
    run: melos exec --category=flutter_projects -- flutter test 
    description: Run flutter test
    packageFilters:
      dirExists: test

  test:dart:
    run: melos exec --category=dart_projects -- dart test
    description: Run dart test
    packageFilters:
      dirExists: test

  test:coverage:
    run: melos exec --category=flutter_projects -- flutter test --coverage
    description: Run flutter test with coverage
    packageFilters:
      dirExists: test

  brb:
    run: melos run gen:build
    
  brbc: 
    run: melos run gen:clean
  fix:
    run: melos run lint:fix:all
  custom_lint_analyze:
    run: melos exec --depends-on="mix_lint" dart pub run custom_lint

  exports:
    run: melos exec --scope="mix" --scope="remix" dart run ../../scripts/exports.dart .
    description: Generate exports for the mix package
  
  verify_version_pubspec_changelog:
    run: ./scripts/verify_changelogs.sh packages
    description: Verify that all packages have the same version