name: mix_markdown_example
description: "Demo app for the mix_markdown renderer."
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  mix: ^2.2.0-beta.5
  mix_markdown:
    path: ..

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
