name: simples_design_system
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  mix: 1.6.0
  mix_annotations: 0.4.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mix_generator: 0.4.0
  build_runner: any

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
