/// Exhaustive field manifest for every styler contributed by mix_chart v1.
const mixChartStylerInventory = {
  'BarBackgroundStyler': {
    ..._stylerMetadataInventory,
    'show',
    'fromY',
    'toY',
    'color',
    'gradient',
  },
  'BarChartStyler': {
    ..._stylerMetadataInventory,
    'frame',
    'axis',
    'xAxis',
    'yAxis',
    'topAxis',
    'rightAxis',
    'grid',
    'bar',
    'segment',
    'palette',
    'groupSpacing',
    'barSpacing',
    'alignment',
    'tooltip',
  },
  'BarSegmentStyler': {
    ..._stylerMetadataInventory,
    'color',
    'gradient',
    'border',
    'label',
  },
  'BarStyler': {
    ..._stylerMetadataInventory,
    'color',
    'gradient',
    'width',
    'borderRadius',
    'border',
    'borderDashArray',
    'background',
    'label',
    'labelOffset',
    'labelAngle',
  },
  'ChartAreaStyler': {
    ..._stylerMetadataInventory,
    'show',
    'color',
    'gradient',
    'cutoffY',
    'applyCutoff',
  },
  'ChartAxisStyler': {
    ..._stylerMetadataInventory,
    'showLabels',
    'label',
    'reservedSize',
    'labelSpace',
    'labelAngle',
    'fitInside',
    'fitInsideDistance',
    'nameSize',
    'drawBelowEverything',
    'alignment',
  },
  'ChartFrameStyler': {
    ..._stylerMetadataInventory,
    'backgroundColor',
    'border',
    'showBorder',
    'clip',
    'rotationQuarterTurns',
  },
  'ChartGridStyler': {
    ..._stylerMetadataInventory,
    'show',
    'showHorizontal',
    'showVertical',
    'horizontalInterval',
    'verticalInterval',
    'stroke',
  },
  'ChartMarkerStyler': {
    ..._stylerMetadataInventory,
    'show',
    'shape',
    'color',
    'radius',
    'borderColor',
    'borderWidth',
    'shadow',
  },
  'ChartStrokeStyler': {
    ..._stylerMetadataInventory,
    'color',
    'gradient',
    'width',
    'dashArray',
    'opacity',
  },
  'ChartTooltipStyler': {
    ..._stylerMetadataInventory,
    'backgroundColor',
    'border',
    'borderRadius',
    'padding',
    'margin',
    'maxWidth',
    'fitHorizontally',
    'fitVertically',
    'text',
  },
  'LineChartStyler': {
    ..._stylerMetadataInventory,
    'frame',
    'axis',
    'xAxis',
    'yAxis',
    'topAxis',
    'rightAxis',
    'grid',
    'series',
    'palette',
    'tooltip',
  },
  'LineSeriesStyler': {
    ..._stylerMetadataInventory,
    'show',
    'stroke',
    'curve',
    'smoothness',
    'preventCurveOvershooting',
    'curveOvershootingThreshold',
    'roundStrokeCap',
    'roundStrokeJoin',
    'marker',
    'belowArea',
    'aboveArea',
    'shadow',
  },
  'PieChartStyler': {
    ..._stylerMetadataInventory,
    'frame',
    'slice',
    'selectedSliceRadiusOffset',
    'palette',
    'centerRadius',
    'centerColor',
    'sliceSpacing',
    'startAngle',
    'sunbeamLabels',
    'tooltip',
  },
  'PieSliceStyler': {
    ..._stylerMetadataInventory,
    'color',
    'gradient',
    'radius',
    'showLabel',
    'label',
    'labelPosition',
    'border',
    'cornerRadius',
    'badgePosition',
  },
};

const _stylerMetadataInventory = {'animation', 'modifier', 'variants'};
