/// Clean-build coverage for `@MixWidget` factories that return a Styler
/// generated by `@MixableSpec` in the same build.
///
/// The generated Styler (`ButtonStyler`) only exists in the combined
/// `.g.dart` part, so it never resolves while `MixWidgetGenerator` runs — the
/// factory return type is `InvalidType`. These tests run both generators in
/// one `PartBuilder` (the same shape as the real `combining_builder`
/// pipeline) and assert the combined output resolves, exercising enum variant
/// constructors and `widgetParameters` curation on the generated-styler path.
library;

import 'package:build/build.dart';
import 'package:build_test/build_test.dart';
import 'package:mix_generator/mix_generator.dart';
import 'package:source_gen/source_gen.dart';
import 'package:test/test.dart';

import '../core/test_helpers.dart';

/// `package:mix` stub surface (Spec/Style/MixStyler/StyleWidget/Prop/MixOps)
/// declared at the real paths so the URL-based type checkers match.
const _mixStub = r'''
  import 'package:flutter/foundation.dart';
  import 'src/core/mix_element.dart';
  import 'src/core/style_spec.dart';

  export 'src/core/mix_element.dart';
  export 'src/core/style_spec.dart';

  abstract class Spec<T extends Spec<T>> {
    const Spec();
  }

  abstract class Style<S extends Spec<S>> extends Mix<StyleSpec<S>> {
    final List<VariantStyle<S>>? $variants;
    final WidgetModifierConfig? $modifier;
    final AnimationConfig? $animation;

    const Style({
      List<VariantStyle<S>>? variants,
      WidgetModifierConfig? modifier,
      AnimationConfig? animation,
    }) : $variants = variants,
         $modifier = modifier,
         $animation = animation;
  }

  abstract class MixStyler<ST extends Style<SP>, SP extends Spec<SP>>
      extends Style<SP> with Diagnosticable {
    const MixStyler({super.variants, super.modifier, super.animation});
  }

  class AnimationConfig {}
  class WidgetModifierConfig {
    Object? resolve(Object context) => null;
  }
  class VariantStyle<S extends Spec<S>> {}

  class Prop<T> {
    static Prop<T>? maybe<T>(T? value) => null;
    static Prop<T>? maybeMix<T>(Object? value) => null;
    static Prop<T>? mix<T>(Object value) => null;
  }

  class MixOps {
    static Prop<T>? merge<T>(Prop<T>? a, Prop<T>? b) => null;
    static List<VariantStyle<S>>? mergeVariants<S extends Spec<S>>(
      List<VariantStyle<S>>? a,
      List<VariantStyle<S>>? b,
    ) => null;
    static WidgetModifierConfig? mergeModifier(
      WidgetModifierConfig? a,
      WidgetModifierConfig? b,
    ) => null;
    static AnimationConfig? mergeAnimation(
      AnimationConfig? a,
      AnimationConfig? b,
    ) => null;
    static T? resolve<T>(Object context, Prop<T>? prop) => null;
  }

  class Color {
    const Color(int value);
  }
''';

const _mixSources = {
  'mix|lib/mix.dart': _mixStub,
  'mix|lib/src/core/mix_element.dart': '''
    abstract class Mix<T> {
      const Mix();
    }
  ''',
  'mix|lib/src/core/style_spec.dart': '''
    import '../../mix.dart';

    class StyleSpec<S extends Spec<S>> {
      const StyleSpec({
        required S spec,
        Object? animation,
        Object? widgetModifiers,
      });
    }
  ''',
  'mix|lib/src/core/style_widget.dart': '''
    import 'package:flutter/widgets.dart';
    import 'package:mix/mix.dart';

    abstract class StyleWidget<S extends Spec<S>> extends Widget {
      final Style<S> style;
      final StyleSpec<S>? styleSpec;

      const StyleWidget({
        required this.style,
        this.styleSpec,
        super.key,
      });
    }
  ''',
};

const _flutterResolveStubs = {
  'flutter|lib/foundation.dart': '''
    class DiagnosticPropertiesBuilder {
      void add(Object? property) {}
    }

    class DiagnosticsProperty<T> {
      const DiagnosticsProperty(String name, T value);
    }

    mixin Diagnosticable {
      void debugFillProperties(DiagnosticPropertiesBuilder properties) {}
    }
  ''',
  'flutter|lib/src/foundation/key.dart': '''
    class Key {
      const Key();
    }
  ''',
  'flutter|lib/src/widgets/framework.dart': '''
    import '../foundation/key.dart';
    export '../foundation/key.dart';

    abstract class Widget {
      const Widget({this.key});
      final Key? key;
    }

    abstract class StatelessWidget extends Widget {
      const StatelessWidget({super.key});
      Widget build(BuildContext context);
    }

    class BuildContext {}
  ''',
  'flutter|lib/widgets.dart': '''
    export 'foundation.dart';
    export 'src/widgets/framework.dart';
  ''',
};

/// Combined `SpecStylerGenerator` + `MixWidgetGenerator` into one `.g.dart`
/// part — the same aggregation the real `combining_builder` performs, so the
/// generated `ButtonStyler` is only ever visible after both generators run.
Builder _combinedBuilder() => PartBuilder([
  const SpecStylerGenerator(),
  const MixWidgetGenerator(),
], '.g.dart');

Map<String, String> _sources(String body) => {
  ...mixAnnotationsSources,
  ..._flutterResolveStubs,
  ..._mixSources,
  'mix|lib/button.dart':
      '''
library button;

import 'package:flutter/widgets.dart';
import 'package:mix/mix.dart';
import 'package:mix/src/core/style_widget.dart';
import 'package:mix_annotations/mix_annotations.dart';

part 'button.g.dart';

class ButtonWidget extends StyleWidget<ButtonSpec> {
  const ButtonWidget({
    super.key,
    required super.style,
    super.styleSpec,
    required this.label,
    this.child,
  });

  final String label;
  final Widget? child;
}

$body
''',
};

/// Runs only `MixWidgetGenerator` and returns its joined error output.
Future<String> _expectMixWidgetError(String body) async {
  final result = await testBuilder(
    partBuilder(const MixWidgetGenerator()),
    _sources(body),
    generateFor: {'mix|lib/button.dart'},
  );

  expect(result.succeeded, isFalse);

  return result.errors.join('\n');
}

void main() {
  group('MixWidget consuming a same-build @MixableSpec styler', () {
    test('generates the widget from the generated styler call surface', () async {
      const body = r'''
@MixableSpec(target: ButtonWidget.new)
final class ButtonSpec extends Spec<ButtonSpec> {
  final Color? color;
  const ButtonSpec({this.color});
}

@MixWidget()
ButtonStyler buttonStyle({Color? color}) => ButtonStyler(color: color);
''';

      await expectGeneratorOutputResolves(
        builder: _combinedBuilder(),
        sources: _sources(body),
        inputAsset: 'mix|lib/button.dart',
        outputAsset: 'mix|lib/button.g.dart',
        outputMatcher: allOf([
          // The generated styler and its target-derived call() live in the
          // same part; the widget is generated despite ButtonStyler never
          // resolving during this build.
          contains(
            'class ButtonStyler extends MixStyler<ButtonStyler, ButtonSpec>',
          ),
          contains(
            'ButtonWidget call({Key? key, required String label, Widget? child})',
          ),
          contains('class Button extends StatelessWidget {'),
          // Factory param (color) + curated call params (label, child).
          contains(
            'const Button({super.key, this.color, required this.label, '
            'this.child});',
          ),
          contains('final Color? color;'),
          contains('final String label;'),
          contains('final Widget? child;'),
          // build() delegates through the factory to the styler call().
          contains('buttonStyle('),
          contains(
            '.call(key: this.key, label: this.label, child: this.child)',
          ),
        ]),
      );
    });

    test(
      'supports enum variant constructors on the generated-styler path',
      () async {
        const body = r'''
enum ButtonVariant { solid, ghost }

@MixableSpec(target: ButtonWidget.new)
final class ButtonSpec extends Spec<ButtonSpec> {
  final Color? color;
  const ButtonSpec({this.color});
}

@MixWidget()
ButtonStyler buttonStyle({
  ButtonVariant variant = ButtonVariant.solid,
  Color? color,
}) => ButtonStyler(color: color);
''';

        await expectGeneratorOutputResolves(
          builder: _combinedBuilder(),
          sources: _sources(body),
          inputAsset: 'mix|lib/button.dart',
          outputAsset: 'mix|lib/button.g.dart',
          outputMatcher: allOf([
            contains('class Button extends StatelessWidget {'),
            contains('const Button.solid('),
            contains('const Button.ghost('),
            contains(': variant = ButtonVariant.solid;'),
            contains('required this.label'),
          ]),
        );
      },
    );

    test('supports a variable factory typed as the generated styler', () async {
      const body = r'''
@MixableSpec(target: ButtonWidget.new)
final class ButtonSpec extends Spec<ButtonSpec> {
  final Color? color;
  const ButtonSpec({this.color});
}

@MixWidget()
final ButtonStyler cardStyle = ButtonStyler(color: Color(0xFF000000));
''';

      await expectGeneratorOutputResolves(
        builder: _combinedBuilder(),
        sources: _sources(body),
        inputAsset: 'mix|lib/button.dart',
        outputAsset: 'mix|lib/button.g.dart',
        outputMatcher: allOf([
          contains('class Card extends StatelessWidget {'),
          contains(
            'cardStyle.call(key: this.key, label: this.label, '
            'child: this.child)',
          ),
        ]),
      );
    });

    test(
      'supports widgetParameters curation on the generated-styler path',
      () async {
        const body = r'''
@MixableSpec(target: ButtonWidget.new)
final class ButtonSpec extends Spec<ButtonSpec> {
  final Color? color;
  const ButtonSpec({this.color});
}

@MixWidget(widgetParameters: .only({'label'}))
ButtonStyler buttonStyle({Color? color}) => ButtonStyler(color: color);
''';

        await expectGeneratorOutputResolves(
          builder: _combinedBuilder(),
          sources: _sources(body),
          inputAsset: 'mix|lib/button.dart',
          outputAsset: 'mix|lib/button.g.dart',
          outputMatcher: allOf([
            contains('class Button extends StatelessWidget {'),
            contains('required this.label'),
            // `child` was excluded by the curation.
            isNot(contains('this.child')),
          ]),
        );
      },
    );
  });

  group('MixWidget generated-styler fallback diagnostics', () {
    test('an unresolved return type with no matching spec keeps the original '
        'InvalidType error', () async {
      // `MysteryStyler` is neither in source nor derivable from any
      // `@MixableSpec`, so the fallback must not fire — the original
      // diagnostic has to stand.
      const body = r'''
@MixWidget()
MysteryStyler mysteryStyle() => throw UnimplementedError();
''';

      final errors = await _expectMixWidgetError(body);

      expect(
        errors,
        contains(
          '@MixWidget target must resolve to a Style<S> subtype, but got '
          '`InvalidType`.',
        ),
      );
    });

    test(
      'a generated styler whose spec has no target reports a clear error',
      () async {
        const body = r'''
@MixableSpec()
final class ButtonSpec extends Spec<ButtonSpec> {
  final Color? color;
  const ButtonSpec({this.color});
}

@MixWidget()
ButtonStyler buttonStyle() => throw UnimplementedError();
''';

        final errors = await _expectMixWidgetError(body);

        expect(
          errors,
          allOf([
            contains('same-build generated styler `ButtonStyler`'),
            contains('`@MixableSpec` on `ButtonSpec` declares no `target:`'),
          ]),
        );
      },
    );
  });

  group('MixWidget plain widget targets', () {
    test('generates a direct plain StatelessWidget wrapper with independent '
        'factory and widget filtering', () async {
      const body = r'''
enum ButtonVariant { solid, ghost }
enum ButtonSize { small, large }

@MixableSpec()
final class ButtonSpec extends Spec<ButtonSpec> {
  final Color? color;
  const ButtonSpec({this.color});
}

class PlainButton extends StatelessWidget {
  const PlainButton({
    super.key,
    required this.label,
    this.child,
    required this.style,
    this.styleSpec,
    this.transitionBuilder = defaultTransitionBuilder,
  });

  static Widget defaultTransitionBuilder(Widget child) => child;

  final String label;
  final Widget? child;
  final Style<ButtonSpec> style;
  final StyleSpec<ButtonSpec>? styleSpec;
  final Widget Function(Widget) transitionBuilder;

  @override
  Widget build(BuildContext context) => child ?? const _Leaf();
}

class _Leaf extends Widget {
  const _Leaf();
}

@MixWidget(
  name: 'FortalButton',
  target: PlainButton.new,
  widgetParameters: .only({'label', 'child', 'transitionBuilder'}),
  factoryParameters: .only({'variant', 'size'}),
)
ButtonStyler fortalButtonStyler({
  ButtonVariant variant = ButtonVariant.solid,
  ButtonSize size = ButtonSize.small,
  bool highContrast = false,
}) => ButtonStyler();
''';

      await expectGeneratorOutputResolves(
        builder: _combinedBuilder(),
        sources: _sources(body),
        inputAsset: 'mix|lib/button.dart',
        outputAsset: 'mix|lib/button.g.dart',
        outputMatcher: allOf([
          contains('class FortalButton extends StatelessWidget {'),
          contains('const FortalButton({'),
          contains('this.variant = ButtonVariant.solid,'),
          contains('this.size = ButtonSize.small,'),
          contains('required this.label,'),
          contains('const FortalButton.solid('),
          contains('const FortalButton.ghost('),
          contains('final ButtonVariant variant;'),
          contains('final ButtonSize size;'),
          contains('final String label;'),
          contains('final Widget? child;'),
          contains(
            'this.transitionBuilder = PlainButton.defaultTransitionBuilder,',
          ),
          isNot(contains('final bool highContrast;')),
          isNot(contains('final Style<ButtonSpec> style;')),
          isNot(contains('final StyleSpec<ButtonSpec>? styleSpec;')),
          contains('return PlainButton('),
          contains('key: this.key,'),
          contains(
            'style: fortalButtonStyler(variant: this.variant, '
            'size: this.size),',
          ),
          contains('label: this.label,'),
          contains('child: this.child,'),
          isNot(contains('.call(')),
        ]),
      );
    });

    test('preserves generic target type parameters', () async {
      const body = r'''
final class ButtonSpec extends Spec<ButtonSpec> {
  const ButtonSpec();
}

@MixableSpec()
final class RadioSpec extends Spec<RadioSpec> {
  const RadioSpec();
}

class PlainRadio<T extends Object> extends StatelessWidget {
  const PlainRadio({
    super.key,
    required this.value,
    required this.style,
    this.styleSpec,
  });

  final T value;
  final Style<RadioSpec> style;
  final StyleSpec<RadioSpec>? styleSpec;

  @override
  Widget build(BuildContext context) => const _Leaf();
}

class _Leaf extends Widget {
  const _Leaf();
}

@MixWidget(name: 'FortalRadio', target: PlainRadio.new)
RadioStyler fortalRadioStyler() => RadioStyler();
''';

      await expectGeneratorOutputResolves(
        builder: _combinedBuilder(),
        sources: _sources(body),
        inputAsset: 'mix|lib/button.dart',
        outputAsset: 'mix|lib/button.g.dart',
        outputMatcher: allOf([
          contains(
            'class FortalRadio<T extends Object> extends StatelessWidget',
          ),
          contains('final T value;'),
          contains('return PlainRadio<T>('),
          contains('style: fortalRadioStyler(),'),
          contains('value: this.value,'),
        ]),
      );
    });

    test('rejects a target without a named style parameter', () async {
      const body = r'''
@MixableSpec()
final class ButtonSpec extends Spec<ButtonSpec> {
  const ButtonSpec();
}

class PlainButton extends StatelessWidget {
  const PlainButton({super.key, required this.label});
  final String label;
  @override
  Widget build(BuildContext context) => const _Leaf();
}

class _Leaf extends Widget {
  const _Leaf();
}

@MixWidget(target: PlainButton.new)
ButtonStyler buttonStyle() => ButtonStyler();
''';

      final errors = await _expectMixWidgetError(body);

      expect(
        errors,
        contains(
          '@MixWidget(target:) requires PlainButton to expose a named '
          '`style` constructor parameter',
        ),
      );
    });

    test('rejects an incompatible target style parameter', () async {
      const body = r'''
@MixableSpec()
final class ButtonSpec extends Spec<ButtonSpec> {
  const ButtonSpec();
}

class PlainButton extends StatelessWidget {
  const PlainButton({super.key, required this.label, required this.style});
  final String label;
  final int style;
  @override
  Widget build(BuildContext context) => const _Leaf();
}

class _Leaf extends Widget {
  const _Leaf();
}

@MixWidget(target: PlainButton.new)
ButtonStyler buttonStyle() => ButtonStyler();
''';

      final errors = await _expectMixWidgetError(body);

      expect(
        errors,
        contains(
          '@MixWidget(target:) PlainButton `style` parameter cannot accept '
          'the `ButtonStyler` recipe result',
        ),
      );
    });

    test('rejects required factory parameters omitted from only', () async {
      const body = r'''
@MixableSpec()
final class ButtonSpec extends Spec<ButtonSpec> {
  const ButtonSpec();
}

class PlainButton extends StatelessWidget {
  const PlainButton({super.key, required this.label, required this.style});
  final String label;
  final Style<ButtonSpec> style;
  @override
  Widget build(BuildContext context) => const _Leaf();
}

class _Leaf extends Widget {
  const _Leaf();
}

@MixWidget(
  target: PlainButton.new,
  factoryParameters: .only({}),
)
ButtonStyler buttonStyle({required bool emphasized}) => ButtonStyler();
''';

      final errors = await _expectMixWidgetError(body);

      expect(
        errors,
        contains(
          '@MixWidget factoryParameters must include required factory '
          'parameter `emphasized`',
        ),
      );
    });
  });
}
