///   /\\\\            /\\\\  /\\\\\\\\\\\  /\\\       /\\\
///   \/\\\\\\        /\\\\\\ \/////\\\///  \///\\\   /\\\/
///    \/\\\//\\\    /\\\//\\\     \/\\\       \///\\\\\\/
///     \/\\\\///\\\/\\\/ \/\\\     \/\\\         \//\\\\
///      \/\\\  \///\\\/   \/\\\     \/\\\          \/\\\\
///       \/\\\    \///     \/\\\     \/\\\          /\\\\\\
///        \/\\\             \/\\\     \/\\\        /\\\////\\\
///         \/\\\             \/\\\  /\\\\\\\\\\\  /\\\/   \///\\\
///          \///              \///  \///////////  \///       \///
///
///                        https://fluttermix.com
///
///             /\///////////////////////////////////////////////////\
///             \/\           ***** GENERATED CODE *****            \ \
///              \/\            ** DO NOT EDIT THIS FILE **          \ \
///               \/\             Generated with barrel script        \ \
///                \/////////////////////////////////////////////////////

library;

/// ANIMATION
export 'src/animation/animation_config.dart';
export 'src/animation/spring_curves.dart';
export 'src/animation/style_animation_builder.dart';
export 'src/animation/style_animation_driver.dart';

/// CORE
export 'src/core/breakpoint.dart';
export 'src/core/converter_registry.dart';
export 'src/core/converter_registry_init.dart';
export 'src/core/directive.dart';
export 'src/core/extensions/extensions.dart';
export 'src/core/extensions/prop_number_ext.dart';
export 'src/core/helpers.dart';
export 'src/core/mix_element.dart';
export 'src/core/pointer_position.dart';
export 'src/core/prop.dart';
export 'src/core/prop_refs.dart';
export 'src/core/prop_source.dart';
export 'src/core/providers/style_provider.dart';
export 'src/core/providers/style_spec_provider.dart';
export 'src/core/providers/widget_state_provider.dart';
export 'src/core/providers/widget_state_style_override.dart';
export 'src/core/spec.dart';
export 'src/core/style.dart' hide StyleElement;
export 'src/core/style_builder.dart';
export 'src/core/style_spec.dart';
export 'src/core/style_widget.dart';
export 'src/core/widget_modifier.dart';

/// MODIFIERS
export 'src/modifiers/align_modifier.dart';
export 'src/modifiers/aspect_ratio_modifier.dart';
export 'src/modifiers/blur_modifier.dart';
export 'src/modifiers/box_modifier.dart';
export 'src/modifiers/clip_modifier.dart';
export 'src/modifiers/default_text_style_modifier.dart';
export 'src/modifiers/default_text_styler_modifier.dart';
export 'src/modifiers/flexible_modifier.dart';
export 'src/modifiers/fractionally_sized_box_modifier.dart';
export 'src/modifiers/icon_theme_modifier.dart';
export 'src/modifiers/internal/reset_modifier.dart';
export 'src/modifiers/intrinsic_modifier.dart';
export 'src/modifiers/mouse_cursor_modifier.dart';
export 'src/modifiers/opacity_modifier.dart';
export 'src/modifiers/padding_modifier.dart';
export 'src/modifiers/rotated_box_modifier.dart';
export 'src/modifiers/scroll_view_modifier.dart';
export 'src/modifiers/shader_mask_modifier.dart';
export 'src/modifiers/sized_box_modifier.dart';
export 'src/modifiers/transform_modifier.dart';
export 'src/modifiers/visibility_modifier.dart';
export 'src/modifiers/widget_modifier_config.dart';

/// PROPERTIES
export 'src/properties/layout/constraints_mix.dart';
export 'src/properties/layout/edge_insets_geometry_mix.dart';
export 'src/properties/layout/stack_mix.dart';
export 'src/properties/painting/border_mix.dart';
export 'src/properties/painting/border_radius_mix.dart';
export 'src/properties/painting/decoration_image_mix.dart';
export 'src/properties/painting/decoration_mix.dart';
export 'src/properties/painting/gradient_mix.dart';
export 'src/properties/painting/shadow_mix.dart';
export 'src/properties/painting/shape_border_mix.dart';
export 'src/properties/typography/strut_style_mix.dart';
export 'src/properties/typography/text_height_behavior_mix.dart';
export 'src/properties/typography/text_style_mix.dart';

/// PROVIDERS
export 'src/providers/icon_scope.dart';
export 'src/providers/text_scope.dart';

/// SPECS
export 'src/specs/box/box_spec.dart';
export 'src/specs/box/box_widget.dart';
export 'src/specs/flex/flex_spec.dart';
export 'src/specs/flexbox/flexbox_spec.dart';
export 'src/specs/flexbox/flexbox_widget.dart';
export 'src/specs/icon/icon_spec.dart';
export 'src/specs/icon/icon_widget.dart';
export 'src/specs/image/image_spec.dart';
export 'src/specs/image/image_widget.dart';
export 'src/specs/pressable/pressable_widget.dart';
export 'src/specs/stack/stack_spec.dart';
export 'src/specs/stackbox/stackbox_spec.dart';
export 'src/specs/stackbox/stackbox_widget.dart';
export 'src/specs/text/text_spec.dart';
export 'src/specs/text/text_widget.dart';

/// STYLE
export 'src/style/abstracts/styler.dart';
export 'src/style/mixins/animation_style_mixin.dart';
export 'src/style/mixins/border_radius_style_mixin.dart';
export 'src/style/mixins/border_style_mixin.dart';
export 'src/style/mixins/constraint_style_mixin.dart';
export 'src/style/mixins/decoration_style_mixin.dart';
export 'src/style/mixins/flex_style_mixin.dart';
export 'src/style/mixins/shadow_style_mixin.dart';
export 'src/style/mixins/spacing_style_mixin.dart';
export 'src/style/mixins/text_style_mixin.dart';
export 'src/style/mixins/transform_style_mixin.dart';
export 'src/style/mixins/variant_style_mixin.dart';
export 'src/style/mixins/widget_modifier_style_mixin.dart';
export 'src/style/mixins/widget_state_variant_mixin.dart';

/// THEME
export 'src/theme/material/material_theme.dart';
export 'src/theme/material/material_tokens.dart';
export 'src/theme/mix_colors.dart';
export 'src/theme/mix_theme.dart';
export 'src/theme/tokens/mix_token.dart';
export 'src/theme/tokens/token_refs.dart'
    hide clearTokenRegistry, getTokenFromValue;
export 'src/theme/tokens/value_tokens.dart';

/// VARIANTS
export 'src/variants/variant.dart';
