/// This file is generated by the update_exports.dart script.
/// DO NOT MODIFY MANUALLY

// Automated file exports
export '../modifiers/align_widget_modifier.dart';
export '../modifiers/aspect_ratio_widget_modifier.dart';
export '../modifiers/clip_widget_modifier.dart';
export '../modifiers/flexible_widget_modifier.dart';
export '../modifiers/fractionally_sized_box_widget_modifier.dart';
export '../modifiers/intrinsic_widget_modifier.dart';
export '../modifiers/opacity_widget_modifier.dart';
export '../modifiers/padding_widget_modifier.dart';
export '../modifiers/render_widget_modifier.dart';
export '../modifiers/rotated_box_widget_modifier.dart';
export '../modifiers/sized_box_widget_modifier.dart';
export '../modifiers/transform_widget_modifier.dart';
export '../modifiers/visibility_widget_modifier.dart';
