///   /\\\\            /\\\\  /\\\\\\\\\\\  /\\\       /\\\
///   \/\\\\\\        /\\\\\\ \/////\\\///  \///\\\   /\\\/
///    \/\\\//\\\    /\\\//\\\     \/\\\       \///\\\\\\/
///     \/\\\\///\\\/\\\/ \/\\\     \/\\\         \//\\\\
///      \/\\\  \///\\\/   \/\\\     \/\\\          \/\\\\
///       \/\\\    \///     \/\\\     \/\\\          /\\\\\\
///        \/\\\             \/\\\     \/\\\        /\\\////\\\
///         \/\\\             \/\\\  /\\\\\\\\\\\  /\\\/   \///\\\
///          \///              \///  \///////////  \///       \///
///
///                        https://fluttermix.com
///
///             /\///////////////////////////////////////////////////\
///             \/\           ***** GENERATED CODE *****            \ \
///              \/\            ** DO NOT EDIT THIS FILE **          \ \
///               \/\             Generated with barrel script        \ \
///                \/////////////////////////////////////////////////////

library remix;

/// COMPONENTS
export 'src/components/accordion/accordion.dart';
export 'src/components/avatar/avatar.dart';
export 'src/components/badge/badge.dart';
export 'src/components/button/button.dart';
export 'src/components/callout/callout.dart';
export 'src/components/card/card.dart';
export 'src/components/checkbox/checkbox.dart';
export 'src/components/chip/chip.dart';
export 'src/components/dialog/dialog.dart';
export 'src/components/divider/divider.dart';
export 'src/components/icon_button/icon_button.dart';
export 'src/components/menu_item/menu_item.dart';
export 'src/components/progress/progress.dart';
export 'src/components/radio/radio.dart';
export 'src/components/scaffold/scaffold.dart';
export 'src/components/segmented_control/segmented_control.dart';
export 'src/components/select/select.dart';
export 'src/components/slider/slider.dart';
export 'src/components/spinner/spinner.dart';
export 'src/components/switch/switch.dart';
export 'src/components/textfield/textfield.dart';
export 'src/components/toast/toast.dart';

/// APP
export 'src/core/remix_app.dart';
export 'src/core/theme/component.dart';

/// THEME
export 'src/core/theme/remix_theme.dart';

/// HELPERS
export 'src/helpers/color_palette.dart';
export 'src/helpers/color_utils.dart';
export 'src/helpers/component_builder.dart';
export 'src/helpers/context_ext.dart';
export 'src/helpers/spec/composited_transform_follower_spec.dart';
export 'src/helpers/utility_extension.dart';
