include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - empty_statements
    - hash_and_equals
    - package_api_docs
    - package_prefixed_library_names
    - prefer_final_fields
    - prefer_single_quotes
    - test_types_in_equals
    - throw_in_finally
    - unawaited_futures
    # Rules that enforce Naked Component conventions
    - camel_case_types
    - library_prefixes
    - avoid_bool_literals_in_conditional_expressions
    - prefer_is_empty
    - prefer_is_not_empty

# Custom lint rules
# Note: These comments serve as documentation since we don't have a formal way
# to enforce these in standard lint rules
#
# Property naming conventions:
# - Boolean state properties should use 'is' prefix (e.g., isDisabled, isChecked)
# - Callbacks should use 'on' prefix (e.g., onPressed, onHoverState)
# - State callbacks should use 'on{State}State' prefix (e.g., onHoverState, onFocusState)

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
