#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

# Find the absolute path to the fvm command
FVM_PATH=$(command -v fvm)

# Check if fvm command is found
if [ -n "$FVM_PATH" ]; then
  # Add the directory containing the fvm command to PATH
  export PATH="$(dirname "$FVM_PATH"):$PATH"
else
  echo "FVM not found. Please make sure it is installed and accessible."
  exit 1
fi

dart run lint_staged


# dart format --line-length 80 --set-exit-if-changed lib test
# dart analyze --fatal-infos --fatal-warnings lib test
# dart test

# branch_name=$(git rev-parse --abbrev-ref HEAD)

# if ! [[ $branch_name =~ ^(feat/|fix/|docs/|style/|refactor/|perf/|test/|build/|ci/|chore/|revert/).+ ]]; then
#   echo "Invalid branch name. Branch names must start with one of the following prefixes followed by a forward slash:"
#   echo "feat/, fix/, docs/, style/, refactor/, perf/, test/, build/, ci/, chore/, revert/"
#   echo "Example: feat/new-feature"
#   exit 1
# fi


