#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

dart --version
# dart format --line-length 80 --set-exit-if-changed lib test
# dart analyze --fatal-infos --fatal-warnings lib test
# dart test

# branch_name=$(git rev-parse --abbrev-ref HEAD)

# if ! [[ $branch_name =~ ^(feat/|fix/|docs/|style/|refactor/|perf/|test/|build/|ci/|chore/|revert/).+ ]]; then
#   echo "Invalid branch name. Branch names must start with one of the following prefixes followed by a forward slash:"
#   echo "feat/, fix/, docs/, style/, refactor/, perf/, test/, build/, ci/, chore/, revert/"
#   echo "Example: feat/new-feature"
#   exit 1
# fi

# dart test
