#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run the dart analysis and format the code before commit
source ~/.zshrc


dart analyze . --fatal-infos
dcm format lib --fatal-found
dart run ./tool/update_exports.dart