name: Add issues to AI Initiatives board

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/btwld/projects/6
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
