name: Publish to pub.dev

on:
  push:
    tags:
      - 'mix-v[0-9]+.[0-9]+.[0-9]+*'
      - 'mix_annotations-v[0-9]+.[0-9]+.[0-9]+*'
      - 'mix_generator-v[0-9]+.[0-9]+.[0-9]+*'
      - 'mix_lint-v[0-9]+.[0-9]+.[0-9]+*'
      - 'mix_winds-v[0-9]+.[0-9]+.[0-9]+*'
      - 'mix_chart-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish_mix:
    if: startsWith(github.ref_name, 'mix-v')
    uses: conceptadev/dart-actions/.github/workflows/publish.yml@main
    with:
      packages_folder_path: "packages"
      packages: |
        mix
    permissions:
      id-token: write
      contents: read

  publish_mix_annotations:
    if: startsWith(github.ref_name, 'mix_annotations-v')
    uses: conceptadev/dart-actions/.github/workflows/publish.yml@main
    with:
      packages_folder_path: "packages"
      packages: |
        mix_annotations
    permissions:
      id-token: write
      contents: read

  publish_mix_generator:
    if: startsWith(github.ref_name, 'mix_generator-v')
    uses: conceptadev/dart-actions/.github/workflows/publish.yml@main
    with:
      packages_folder_path: "packages"
      packages: |
        mix_generator
    permissions:
      id-token: write
      contents: read

  publish_mix_lint:
    if: startsWith(github.ref_name, 'mix_lint-v')
    uses: conceptadev/dart-actions/.github/workflows/publish.yml@main
    with:
      packages_folder_path: "packages"
      packages: |
        mix_lint
    permissions:
      id-token: write
      contents: read

  publish_mix_winds:
    if: startsWith(github.ref_name, 'mix_winds-v')
    uses: conceptadev/dart-actions/.github/workflows/publish.yml@main
    with:
      packages_folder_path: "packages"
      packages: |
        mix_winds
    permissions:
      id-token: write
      contents: read

  publish_mix_chart:
    if: startsWith(github.ref_name, 'mix_chart-v')
    uses: conceptadev/dart-actions/.github/workflows/publish.yml@main
    with:
      packages_folder_path: "packages"
      packages: |
        mix_chart
    permissions:
      id-token: write
      contents: read
